# Generated by Django 6.0.2 on 2026-02-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('icon_class', models.CharField(blank=True, help_text='Например: bi-trash', max_length=50, verbose_name='Иконка Bootstrap')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория отходов',
                'verbose_name_plural': 'Категории отходов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SortingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Что сдаем?')),
                ('description', models.TextField(verbose_name='Как подготовить к сдаче')),
                ('is_recyclable', models.BooleanField(default=True, verbose_name='Перерабатывается?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sorting.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Правило сортировки',
                'verbose_name_plural': 'Правила сортировки',
            },
        ),
    ]
