# Generated by Django 6.0.2 on 2026-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipation',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Фото-подтверждение'),
        ),
    ]
