# Generated by Django 6.0.2 on 2026-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Пункт приёма', 'verbose_name_plural': 'Пункты приёма'},
        ),
        migrations.AddField(
            model_name='location',
            name='accepts_batteries',
            field=models.BooleanField(default=False, verbose_name='Принимает батарейки/электронику'),
        ),
        migrations.AddField(
            model_name='location',
            name='accepts_glass',
            field=models.BooleanField(default=False, verbose_name='Принимает стекло'),
        ),
        migrations.AddField(
            model_name='location',
            name='accepts_paper',
            field=models.BooleanField(default=False, verbose_name='Принимает макулатуру'),
        ),
        migrations.AddField(
            model_name='location',
            name='accepts_plastic',
            field=models.BooleanField(default=False, verbose_name='Принимает пластик'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название пункта'),
        ),
    ]
