# Generated by Django 6.0.2 on 2026-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_options_location_accepts_batteries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Например: Пн-Пт: 09:00 - 18:00', max_length=100, verbose_name='Время работы (Пн-Вс)'),
        ),
    ]
